import { GoogleGenerativeAI, SchemaType } from '@google/generative-ai';

/**
 * Desired length of the summary.
 */
export type SummaryLength = 'short' | 'medium' | 'long';

/**
 * How the summary was produced:
 * - 'ai': generated by the Gemini API
 * - 'extractive': generated locally by the keyword-frequency extractive engine
 */
export type SummaryMode = 'ai' | 'extractive';

/**
 * Result structure of the summarization task.
 */
export type SummaryResult = {
  summary: string;
  keyPoints: string[];
  improvementSuggestions: string[];
  mode: SummaryMode;
  /** Optional human-readable note about how/why this result was produced. */
  notice?: string;
};

/**
 * Current stable Gemini model.
 * NOTE: 'gemini-2.0-flash' was shut down by Google on June 1, 2026 — do not use it.
 */
const GEMINI_MODEL = 'gemini-3.6-flash';

/* ------------------------------------------------------------------ */
/* Extractive (local) summarizer                                       */
/* ------------------------------------------------------------------ */

const STOPWORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'if', 'then', 'else', 'when', 'while', 'of', 'at',
  'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before',
  'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over',
  'under', 'again', 'further', 'once', 'here', 'there', 'all', 'any', 'both', 'each', 'few',
  'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so',
  'than', 'too', 'very', 'can', 'will', 'just', 'should', 'now', 'is', 'are', 'was', 'were',
  'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'would',
  'could', 'might', 'must', 'shall', 'may', 'i', 'you', 'he', 'she', 'it', 'we', 'they', 'them',
  'his', 'her', 'its', 'our', 'their', 'this', 'that', 'these', 'those', 'as', 'what', 'which',
  'who', 'whom', 'also', 'per', 'via', 'etc', 'within', 'without', 'across', 'upon', 'onto',
  'among', 'around', 'however', 'therefore', 'thus', 'hence', 'yet', 'still', 'even', 'much',
  'many', 'well', 'because', 'since', 'until', 'unless', 'although', 'though', 'where', 'how',
  'why', 'whether', 'either', 'neither', 'both', 'whether', 'onto', 'unto', 'amid', 'amidst',
]);

type ExtractivePreset = {
  summarySentences: number;
  keyPoints: number;
  suggestions: number;
};

const EXTRACTIVE_PRESETS: Record<SummaryLength, ExtractivePreset> = {
  short: { summarySentences: 2, keyPoints: 3, suggestions: 2 },
  medium: { summarySentences: 4, keyPoints: 5, suggestions: 3 },
  long: { summarySentences: 7, keyPoints: 6, suggestions: 4 },
};

/** Normalizes raw extracted text before analysis. */
function cleanText(raw: string): string {
  return raw
    .replace(/\r\n?/g, '\n')
    // Remove page-break markers injected during extraction
    .replace(/-{2,}\s*Page\s+\d+\s*-{2,}/gi, '\n')
    // Rejoin words split by end-of-line hyphenation ("exam-\nple" -> "example")
    .replace(/(\w)-\n(\w)/g, '$1$2')
    .replace(/[ \t]+/g, ' ')
    .replace(/ ?\n ?/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function tokenize(text: string): string[] {
  return text.toLowerCase().match(/[a-z0-9][a-z0-9'’-]*/g) ?? [];
}

function contentTokens(text: string): string[] {
  return tokenize(text).filter((t) => t.length > 2 && !STOPWORDS.has(t));
}

/** Splits text into sentences, respecting paragraph breaks as hard boundaries. */
function splitSentences(text: string): string[] {
  const sentences: string[] = [];
  for (const paragraph of text.split(/\n+/)) {
    const trimmed = paragraph.trim();
    if (!trimmed) continue;
    // Split after sentence-ending punctuation when followed by a capital/digit/quote.
    const parts = trimmed.split(/(?<=[.!?…])\s+(?=[A-Z0-9"'“‘(\[])/);
    for (const part of parts) {
      const s = part.trim();
      if (s.length > 0) sentences.push(s);
    }
  }
  return sentences;
}

/** Scores every sentence by normalized term-frequency with positional boosts. */
function scoreSentences(sentences: string[], fullText: string): number[] {
  const freq = new Map<string, number>();
  for (const token of contentTokens(fullText)) {
    freq.set(token, (freq.get(token) ?? 0) + 1);
  }
  const maxFreq = Math.max(1, ...freq.values());

  return sentences.map((sentence, index) => {
    const tokens = contentTokens(sentence);
    if (tokens.length === 0) return 0;

    const termScore =
      tokens.reduce((sum, t) => sum + (freq.get(t) ?? 0) / maxFreq, 0) /
      Math.pow(tokens.length, 0.6);

    let score = termScore;

    // Lead bias: document openings usually carry the thesis.
    if (index === 0) score *= 1.35;
    else if (index === 1) score *= 1.2;
    else if (index === 2) score *= 1.1;
    // Mild boost for the closing sentence (conclusions).
    if (index === sentences.length - 1 && sentences.length > 3) score *= 1.05;

    // Sentences with numbers often carry concrete facts.
    if (/\d/.test(sentence)) score *= 1.1;

    // Penalize fragments and run-ons.
    const wordCount = sentence.split(/\s+/).length;
    if (wordCount < 5) score *= 0.4;
    else if (wordCount > 50) score *= 0.8;

    return score;
  });
}

/** Truncates a sentence to a max length at a word boundary. */
function truncateToLength(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  const cut = text.slice(0, maxLength);
  const lastSpace = cut.lastIndexOf(' ');
  return `${cut.slice(0, lastSpace > 80 ? lastSpace : maxLength).trimEnd()}…`;
}

/** Heuristic, statistics-based improvement suggestions (no boilerplate). */
function buildSuggestions(text: string, sentences: string[]): string[] {
  const suggestions: string[] = [];
  const words = text.split(/\s+/).filter(Boolean).length;
  const paragraphs = text.split(/\n{2,}/).filter((p) => p.trim().length > 0);
  const avgSentenceLen = sentences.length > 0 ? words / sentences.length : 0;
  const sentencesWithNumbers = sentences.filter((s) => /\d/.test(s)).length;

  if (avgSentenceLen > 26) {
    suggestions.push(
      `Average sentence length is ${Math.round(avgSentenceLen)} words — splitting sentences over ~30 words would improve readability.`
    );
  }
  if (paragraphs.length <= 2 && words > 300) {
    suggestions.push(
      'The text is one large block — breaking it into sections with descriptive headings would make it easier to scan.'
    );
  }
  if (paragraphs.some((p) => p.length > 600)) {
    suggestions.push(
      'Some paragraphs exceed ~100 words; splitting them would make the document less dense.'
    );
  }
  if (words > 1000) {
    suggestions.push(
      `At ~${words.toLocaleString()} words, adding a short executive overview (TL;DR) at the top would help readers skim.`
    );
  }
  if (sentences.length > 5 && sentencesWithNumbers / sentences.length < 0.08 && words > 300) {
    suggestions.push(
      'Few figures or data points were detected — supporting key claims with metrics would strengthen the document.'
    );
  }

  if (suggestions.length === 0) {
    suggestions.push(
      'No major structural issues detected — a light proofread for consistent terminology and typos is recommended.'
    );
  }
  if (suggestions.length === 1) {
    suggestions.push(
      'Consider adding a one-line conclusion that restates the main takeaway for busy readers.'
    );
  }
  return suggestions;
}

/**
 * Local extractive summarizer: picks the most informative sentences
 * (frequency-scored, position-boosted) instead of blindly taking the first ones.
 */
export function generateExtractiveSummary(text: string, length: SummaryLength): SummaryResult {
  const preset = EXTRACTIVE_PRESETS[length];
  const cleaned = cleanText(text);
  const sentences = splitSentences(cleaned);

  // Very short input: nothing to extract — return it verbatim, clearly labeled.
  if (sentences.length <= 2) {
    return {
      summary: cleaned || text.trim(),
      keyPoints: sentences.length > 0 ? sentences.map((s) => truncateToLength(s, 220)) : ['Document is too short to extract key points.'],
      improvementSuggestions: buildSuggestions(cleaned || text, sentences),
      mode: 'extractive',
    };
  }

  const scores = scoreSentences(sentences, cleaned);
  const ranked = sentences
    .map((sentence, index) => ({ sentence, index, score: scores[index] }))
    .sort((a, b) => b.score - a.score);

  // Summary: top sentences, restored to document order for coherent reading.
  const summaryCount = Math.min(preset.summarySentences, sentences.length);
  const summaryParts = ranked
    .slice(0, summaryCount)
    .sort((a, b) => a.index - b.index)
    .map((r) => r.sentence);

  let summary: string;
  if (length === 'long' && summaryParts.length > 4) {
    const mid = Math.ceil(summaryParts.length / 2);
    summary = `${summaryParts.slice(0, mid).join(' ')}\n\n${summaryParts.slice(mid).join(' ')}`;
  } else {
    summary = summaryParts.join(' ');
  }

  // Key points: best sentences not already in the summary; backfill if needed.
  const summarySet = new Set(summaryParts);
  const keyPoints: string[] = [];
  for (const r of ranked) {
    if (keyPoints.length >= preset.keyPoints) break;
    if (!summarySet.has(r.sentence)) keyPoints.push(truncateToLength(r.sentence, 220));
  }
  if (keyPoints.length === 0) {
    for (const r of ranked) {
      if (keyPoints.length >= Math.min(preset.keyPoints, 2)) break;
      keyPoints.push(truncateToLength(r.sentence, 220));
    }
  }

  return {
    summary,
    keyPoints,
    improvementSuggestions: buildSuggestions(cleaned, sentences).slice(0, preset.suggestions),
    mode: 'extractive',
  };
}

/* ------------------------------------------------------------------ */
/* Gemini-powered summarizer                                           */
/* ------------------------------------------------------------------ */

function hasValidApiKey(): boolean {
  const apiKey = process.env.GEMINI_API_KEY;
  return Boolean(apiKey && apiKey.trim() !== '' && apiKey !== 'your_gemini_api_key_here');
}

function lengthInstructions(length: SummaryLength): string {
  switch (length) {
    case 'short':
      return 'The summary must be 2-3 sentences. Return exactly 3 key points and exactly 2 improvement suggestions.';
    case 'medium':
      return 'The summary must be one well-structured paragraph of 5-8 sentences. Return 4-5 key points and exactly 3 improvement suggestions.';
    case 'long':
      return 'The summary must be 3-4 detailed paragraphs (separated by \\n\\n) covering the document comprehensively. Return 6-7 key points and exactly 4 improvement suggestions.';
  }
}

/**
 * Generates a summary for the provided text using the Gemini API.
 * Falls back to the local extractive engine when no API key is configured
 * or the API call fails — always transparently flagged via `mode`/`notice`.
 */
export async function generateSummary(text: string, length: SummaryLength): Promise<SummaryResult> {
  if (!hasValidApiKey()) {
    console.info('No valid GEMINI_API_KEY found — using local extractive summarizer.');
    const result = generateExtractiveSummary(text, length);
    return {
      ...result,
      notice:
        'Demo mode: this extractive summary was generated locally. Add a GEMINI_API_KEY to .env.local for full AI-powered summaries.',
    };
  }

  try {
    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY as string);
    const model = genAI.getGenerativeModel({
      model: GEMINI_MODEL,
      generationConfig: {
        temperature: 0.3,
        responseMimeType: 'application/json',
        responseSchema: {
          type: SchemaType.OBJECT,
          properties: {
            summary: { type: SchemaType.STRING },
            keyPoints: { type: SchemaType.ARRAY, items: { type: SchemaType.STRING } },
            improvementSuggestions: { type: SchemaType.ARRAY, items: { type: SchemaType.STRING } },
          },
          required: ['summary', 'keyPoints', 'improvementSuggestions'],
        },
      },
    });

    const prompt = `You are an expert document analyst. Summarize the document below.

Strict rules:
- Use ONLY information that is present in the document. Never invent facts, names, or numbers.
- Write in the same language as the document.
- ${lengthInstructions(length)}
- "summary" must be plain text (paragraphs separated by \\n\\n). No markdown headings or code fences.
- Each key point must be one concise, self-contained sentence capturing a core message.
- Improvement suggestions must be specific to THIS document's actual structure and content.

Document text:
"""
${text}
"""`;

    const result = await model.generateContent(prompt);
    const responseText = result.response.text();

    if (!responseText || responseText.trim() === '') {
      throw new Error('The model returned an empty response (possibly blocked by safety filters).');
    }

    // responseMimeType: 'application/json' guarantees JSON; strip fences defensively.
    const cleanText = responseText
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/i, '')
      .replace(/\s*```$/, '')
      .trim();

    const parsed = JSON.parse(cleanText) as Partial<SummaryResult>;

    if (typeof parsed.summary !== 'string' || parsed.summary.trim() === '') {
      throw new Error('The model response did not include a usable summary.');
    }

    return {
      summary: parsed.summary.trim(),
      keyPoints: Array.isArray(parsed.keyPoints) ? parsed.keyPoints.filter((k) => typeof k === 'string') : [],
      improvementSuggestions: Array.isArray(parsed.improvementSuggestions)
        ? parsed.improvementSuggestions.filter((s) => typeof s === 'string')
        : [],
      mode: 'ai',
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error('Gemini API call failed:', message);
    const fallback = generateExtractiveSummary(text, length);
    return {
      ...fallback,
      notice: `AI summarization failed (${truncateToLength(message, 160)}). Showing a local extractive summary instead.`,
    };
  }
}
